#!/bin/sh

JFFS_SB_DIR="/jffs/addons/sing-box"
ROOT_DIR="/opt/root"
SB_DIR="$ROOT_DIR/sing-box"
SCRIPT_PATH="$JFFS_SB_DIR/sing-box-script-ru"
SB_DOWNLOAD_DIR="$SB_DIR/sing-box-download"
SB_CONFIG="$JFFS_SB_DIR/config.json"
SCRIPT_URL="https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/sing-box-script-ru"
SB_URL="https://api.github.com/repos/SagerNet/sing-box/releases/latest"
SB_DOWNLOAD_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" "$SB_URL" | grep -o '"browser_download_url":\s*"[^"]*linux-arm64.tar.gz"' | grep -o 'https://.*linux-arm64.tar.gz')
SB_ARCHIVE_PATH="$SB_DOWNLOAD_DIR/sing-box-linux-arm64.tar.gz"

create_dir() {
    mkdir -p "$1"
    chmod 775 "$1"
    echo "Директория $1 создана."
}

dir_exists() {
    [ -d "$1" ]
}

create_script_conf() {
    cat << EOF > "$1"
# Этот файл создаётся автоматически и значения вводятся через консоль при выполнении команды sbs setup.
# Если хотите изменить значения тут с помощью редактора, то перед этим обязательно остановите sing-box через консоль командой sbs stop

# Впишите в кавычки, в одну строку, разделенные пробелами ip-адреса устройств, трафик которых надо направить в tun интерфейс sing-box.
DEVICE_IPS="192.168.50.31 192.168.50.32"

# Здесь это потому, что нужно для работы скрипта монитора маршрута по умолчанию для интерфейса sbtun.
TUN_INTERFACE="sbtun"

# Если указанный дефолтный номер 555 таблицы маршрутизации на вашем маршрутизаторе уже занят, что маловероятно, назначьте другой номер, не занятый. И это тут тоже нужно для работы скрипта монитора маршрута по умолчанию для интерфейса sbtun.
ROUTE_TABLE="555"
EOF
    chmod 664 "$1"
}

create_monitor_routes() {
    cat << EOF > "$1"
#!/bin/sh

source "/jffs/addons/sing-box/sing-box-script-ru.conf"

add_default_route() {
    # Проверяем, существует ли уже маршрут по умолчанию в указанной таблице
    existing_route=$(ip route show table "$ROUTE_TABLE" | grep "default dev $TUN_INTERFACE")
    if [ -z "$existing_route" ]; then
        ip route add default dev "$TUN_INTERFACE" table "$ROUTE_TABLE"
        echo "Маршрут добавлен: ip route add default dev $TUN_INTERFACE table $ROUTE_TABLE"
    fi
}

monitor_routes() {
    ip monitor route | while read -r line; do
        echo "Обнаружено изменение: $line"
        echo "$line" | grep -q "dev $TUN_INTERFACE table"
        if [ $? -eq 0 ]; then
            add_default_route
        fi
    done
}

trap '' SIGHUP

monitor_routes
EOF
    chmod 775 "$1"
}

check_file_existence_and_download() {
    local file_path="$1"
    local file_url="$2"
    local file_name=$(basename "$file_path")

    if [ -f "$file_path" ]; then
        while true; do
            read -p "Файл $file_name уже существует. Что вы хотите сделать? 
(1: Пропустить скачивание, 2: Скачать и заменить файл): " choice
            case $choice in
                1) echo "Пропускаем скачивание $file_name."; return 0 ;;
                2) echo "Скачиваем и заменяем файл $file_name"; curl -s -L -o "$file_path" "$file_url"; return 0 ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        echo "Скачиваем $file_name..."
        curl -s -L -o "$file_path" "$file_url"
    fi
}

create_or_use_existing() {
    local dir_path="$1"
    if dir_exists "$dir_path"; then
        while true; do
            read -p "Директория $dir_path уже существует. Что вы хотите сделать? 
(1: Завершить работу, 2: Использовать существующую директорию): " choice
            case $choice in
                1) rm -rf /jffs/scripts/sb-script-install-ru ; echo "Работа скрипта завершена."; exit 0 ;;
                2) echo "Используем существующую директорию $dir_path"; break ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        create_dir "$dir_path"
    fi
}

handle_existing_file() {
    local file_path="$1"
    local create_function="$2"
    if [ -f "$file_path" ]; then
        while true; do
            read -p "Файл $file_path уже существует. Что вы хотите сделать? 
(1: Оставить существующий файл, 2: Заменить файл): " choice
            case $choice in
                1) echo "Оставляем существующий файл."; break ;;
                2) echo "Заменяем файл $file_path"; "$create_function" "$file_path"; break ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        "$create_function" "$file_path"
    fi
}

create_or_use_existing "$JFFS_SB_DIR"

check_file_existence_and_download "$SCRIPT_PATH" "$SCRIPT_URL"
chmod 775 $SCRIPT_PATH

ln -sf "$SCRIPT_PATH" /opt/bin/sbs

handle_existing_file "$JFFS_SB_DIR/script-conf" create_script_conf

handle_existing_file "$JFFS_SB_DIR/monitor-routes" create_monitor_routes

check_file_existence_and_download "https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/config.json"
chmod 664 "$SB_CONFIG"

if [ -n "$ROOT_DIR" ]; then
    create_or_use_existing "$SB_DIR"
else
    echo "Директория '/opt/root' не найдена. Операция отменена."
    exit 1
fi

create_dir "$SB_DOWNLOAD_DIR"

if [ -z "$SB_DOWNLOAD_URL" ]; then
    echo "Не удалось найти ссылку на скачивание архива."
    exit 1
fi

echo "Скачиваем архив..."
curl -s -L -o "$SB_ARCHIVE_PATH" "$SB_DOWNLOAD_URL"

echo "Распаковываем архив..."
tar -xzvf "$SB_ARCHIVE_PATH" -C "$SB_DOWNLOAD_DIR"

sing_box_file=$(find "$SB_DOWNLOAD_DIR" -name "sing-box" -type f)

if [ -z "$sing_box_file" ]; then
    echo "Не удалось найти файл sing-box в распакованном архиве."
    exit 1
fi

sing_box_path="$SB_DIR/sing-box"
if [ -f "$sing_box_path" ]; then
    while true; do
        read -p "Файл sing-box уже существует. Что вы хотите сделать? 
(1: Оставить существующий файл, 2: Заменить файл): " choice
        case $choice in
            1) echo "Оставляем существующий файл."; break ;;
            2) echo "Заменяем файл $sing_box_path"; cp "$sing_box_file" "$SB_DIR"; chmod 775 "$sing_box_path"; break ;;
            *) echo "Неверный выбор. Попробуйте еще раз." ;;
        esac
    done
else
    cp "$sing_box_file" "$SB_DIR"; echo "Файл sing-box перемещён в директорию $SB_DIR"
fi

rm -rf "$SB_DOWNLOAD_DIR" /jffs/scripts/sing-box-script-install-ru

echo "Директория $SB_DOWNLOAD_DIR удалена."

echo "

*********************
Установка завершена.
*********************
Следующим шагом вы должны отредактировать под себя config.json - файл конфигурации sing-box, расположенный по пути $SB_CONFIG.
Можете сделать это с помощью WinSCP или в консоли роутера командой:
sbs edit
Затем для настройки скрипта sing-box выполнить:
sbs setup
Подсказки по всем командам можете увидеть, выполнив в консоли роутера команду:
sbs"
