#!/bin/sh

# Скрипт для запуска sing-box на роутерах Asus с прошивкой Мерлина и установленным на USB носителе Entware.

# Переменные
JFFS_SB_DIR="/jffs/addons/sing-box-script"
SB_CONFIG="$JFFS_SB_DIR/config.json"
SCRIPT_PATH="$JFFS_SB_DIR/sbs-ru"
SBS_CONF="$JFFS_SB_DIR/sbs-conf"
SBS_MON="$JFFS_SB_DIR/sbs-monitor"
TEMP_UPDATE="$JFFS_SB_DIR/temp-update"
ROOT_DIR="/opt/root"
SB_DIR="$ROOT_DIR/sing-box"
SB_PATH="$SB_DIR/sing-box"
SB_DOWNLOAD_DIR="$SB_DIR/sing-box-download"
SB_ARCHIVE_PATH="$SB_DOWNLOAD_DIR/sing-box-linux-arm64.tar.gz"
SCRIPT_URL="https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/sbs-ru"
SB_URL="https://api.github.com/repos/SagerNet/sing-box/releases/latest"
SB_DOWNLOAD_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" "$SB_URL" | grep -o '"browser_download_url":\s*"[^"]*linux-arm64.tar.gz"' | grep -o 'https://.*linux-arm64.tar.gz')
SS_DIR="/jffs/scripts"
FW_SCRIPT="$SS_DIR/firewall-start"
SS_SCRIPT="$SS_DIR/services-start"
SS_LINES="sleep 30
$SCRIPT_PATH start"
LN_PATH="/opt/bin/sbs"

# Функции
log_msg() {
    echo "$1"
    logger -t "sbs" "$1"
}

create_dir() {
    mkdir -p "$1"
    chmod 775 "$1"
    echo "Директория $1 создана."
}

dir_exists() {
    [ -d "$1" ]
}

create_sbs_conf() {
    cat << EOF > "$1"
# This file is created automatically and the values are entered via the command line when executing the 'sbs setup' command.
# If you want to change the values here using an editor bypassing the 'sbs setup' command, then before doing so, be sure to stop sing-box with the 'sbs stop' command in the command line.

# Enter in quotes on one line, separated by spaces, the IP addresses of the devices whose traffic needs to be directed through the sing-box tun interface.
DEVICE_IPS="192.168.50.31 192.168.50.32"

# If the specified routing table number 555 on your router is already taken, which is unlikely, assign another number that is not taken.
ROUTE_TABLE="555"

# This value is determined automatically. It is here only because it is needed for sbs-monitor to work.
TUN_INTERFACE="sbtun"
EOF
    chmod 664 "$1"
}

create_sbs_monitor() {
    cat << EOF > "$1"
#!/bin/sh

source "$SBS_CONF"

log_msg() {
    echo "\$1"
    logger -t "sbs" "\$1"
}

add_rr() {
    existing_route=\$(ip route show table "\$ROUTE_TABLE" | grep "default dev \$TUN_INTERFACE")
    if [ -z "\$existing_route" ]; then
        ip route add default dev "\$TUN_INTERFACE" table "\$ROUTE_TABLE"
        log_msg "Маршрут добавлен: ip route add default dev \$TUN_INTERFACE table \$ROUTE_TABLE"
    fi
    existing_rule=\$(ip rule show | grep "lookup \$ROUTE_TABLE")
    if [ -z "\$existing_rule" ]; then
        for IP in \$DEVICE_IPS; do ip rule add from \$IP table \$ROUTE_TABLE; done
        log_msg "Правила ip для таблицы маршрутизации \$ROUTE_TABLE добавлены"
    fi
}

sbs_monitor_rr() {
    ip monitor route | while read -r line; do
        log_msg "Обнаружено изменение: \$line"
        echo "\$line" | grep -q "dev \$TUN_INTERFACE table"
        if [ \$? -eq 0 ]; then
            add_rr
        fi
    done
}

trap '' SIGHUP

sbs_monitor_rr
EOF
    chmod 775 "$1"
}

check_file_existence_and_download() {
    local file_path="$1"
    local file_url="$2"
    local file_name=$(basename "$file_path")

    if [ -f "$file_path" ]; then
    echo "Файл $file_name уже существует. Что вы хотите сделать?"
        while true; do
            read -p "1-Пропустить скачивание, 2-Скачать и заменить файл: " choice
            case $choice in
                1) echo "Пропускаем скачивание $file_name."; return 0 ;;
                2) echo "Скачиваем и заменяем файл $file_name"; curl -s -L -o "$file_path" "$file_url"; return 0 ;;
                *) echo "Некорректный ввод. Попробуйте еще раз." ;;
            esac
        done
    else
        echo "Скачиваем $file_name..."
        curl -s -L -o "$file_path" "$file_url"
    fi
}

delete_if_not_current_dir() {
  local current_dir=$(dirname "$(readlink -f "$0")")
  if [ "$current_dir" != "$JFFS_SB_DIR" ]; then
    rm -f "$(readlink -f "$0")"
  fi
}

create_or_use_existing() {
    local dir_path="$1"
    if dir_exists "$dir_path"; then
    echo "Директория $dir_path уже существует. Что вы хотите сделать?"
        while true; do
            read -p "1-Завершить работу, 2-Использовать существующую директорию: " choice
            case $choice in
                1) delete_if_not_current_dir; echo "Работа скрипта завершена."; exit 0 ;;
                2) echo "Используем существующую директорию $dir_path"; break ;;
                *) echo "Некорректный ввод. Попробуйте еще раз." ;;
            esac
        done
    else
        create_dir "$dir_path"
    fi
}

handle_existing_file() {
    local file_path="$1"
    local create_function="$2"
    if [ -f "$file_path" ]; then
    echo "Файл $file_path уже существует. Что вы хотите сделать?"
        while true; do
            read -p "1-Оставить существующий файл, 2-Заменить файл: " choice
            case $choice in
                1) echo "Оставляем существующий файл."; break ;;
                2) echo "Заменяем файл $file_path"; "$create_function" "$file_path"; break ;;
                *) echo "Некорректный ввод. Попробуйте еще раз." ;;
            esac
        done
    else
        "$create_function" "$file_path"
    fi
}

ensure_script() {
    [ -f "$1" ] || { echo "#!/bin/sh" > "$1"; chmod 755 "$1"; }
}

update_script() {
    ensure_script "$1"
    echo "$2" | while read -r line; do
        grep -qF "$line" "$1" || echo "$line" >> "$1"
    done
}

remove_script_content() {
    [ -f "$1" ] && echo "$2" | while read -r line; do
        sed -i "/$(echo "$line" | sed 's/[\/&]/\\&/g')/d" "$1"
    done
}

manage_iptables() {
    if [ "$1" = "add" ]; then
        iptables -C $2 2>/dev/null || iptables -I $2 || log_msg "Error adding iptables rule: $2"
    elif [ "$1" = "remove" ]; then
        iptables -C $2 2>/dev/null && iptables -D $2 || log_msg "Error removing iptables rule: $2"
    fi
}

is_running() {
    ps | grep -v grep | grep -q "$SB_PATH"
}

self_copy() {
    local destination="$1"
    cp "$0" "$destination"
}

sing_box_start() {
    echo "Запустить sing-box?"
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "sing-box не запущен."; break ;;
            2) start_sing_box; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done
}

start_sing_box() {
    log_msg "Запуск sing-box..."

    is_running && { log_msg "Ошибка: sing-box уже запущен."; exit 1; }

    source "$SBS_CONF"

    if [ -f "$SB_CONFIG" ]; then
        local config_content=$(cat "$SB_CONFIG")
        local new_iface=$(echo "$config_content" | grep '"interface_name":' | sed -n 's/.*"interface_name": "\(.*\)".*/\1/p')
        if [ -n "$new_iface" ] && [ "$new_iface" != "$TUN_INTERFACE" ]; then
            TUN_INTERFACE="$new_iface"
            sed -i "s|^TUN_INTERFACE=\".*\"$|TUN_INTERFACE=\"$TUN_INTERFACE\"|" "$SBS_CONF"
            log_msg "Имя интерфейса TUN обновлено на: $TUN_INTERFACE"
        elif [ -z "$new_iface" ]; then
            log_msg "Ошибка: не удалось извлечь имя интерфейса TUN из $SB_CONFIG"
            exit 1
        fi
    else
        log_msg "Ошибка: файл $SB_CONFIG не найден"
        exit 1
    fi

    FW_RULES="FORWARD -i $TUN_INTERFACE -j ACCEPT
    FORWARD -o $TUN_INTERFACE -j ACCEPT
    INPUT -i $TUN_INTERFACE -j ACCEPT
    OUTPUT -o $TUN_INTERFACE -j ACCEPT"

    lsmod | grep -q "^tun " || { log_msg "Загрузка модуля TUN..."; modprobe tun; }

    $SB_PATH run -c $SB_CONFIG &
    sleep 3

    ip link show $TUN_INTERFACE >/dev/null 2>&1 || { log_msg "Ошибка: интерфейс TUN $TUN_INTERFACE не найден"; exit 1; }

    log_msg "Настройка таблицы маршрутизации..."
    ip route add default dev $TUN_INTERFACE table $ROUTE_TABLE
    for IP in $DEVICE_IPS; do ip rule add from $IP table $ROUTE_TABLE; done

    log_msg "Добавление правил фаервола..."
    echo "$FW_RULES" | while read -r rule; do
        manage_iptables "add" "$rule"
    done

    log_msg "Обновление скрипта firewall-start..."
    echo "$FW_RULES" | while read -r rule; do
        update_script "$FW_SCRIPT" "iptables -I $rule"
    done

    log_msg "Обновление скрипта services-start..."
    update_script "$SS_SCRIPT" "$SS_LINES"
    log_msg "sing-box запущен."

    $SBS_MON &
    log_msg "sbs-monitor запущен."
}

stop_sing_box() {
    log_msg "Остановка sing-box..."

    source "$SBS_CONF"

    FW_RULES="FORWARD -i $TUN_INTERFACE -j ACCEPT
    FORWARD -o $TUN_INTERFACE -j ACCEPT
    INPUT -i $TUN_INTERFACE -j ACCEPT
    OUTPUT -o $TUN_INTERFACE -j ACCEPT"

    pids=$(pidof "sbs-monitor")
    if [ -z "$pids" ]; then
      break
    fi
    for pid in $pids; do
      kill "$pid"
    done
    log_msg "sbs-monitor остановлен."

    PIDS=$(pidof "sing-box")
    if [ -z "$PIDS" ]; then
      break
    fi
    for pid in $PIDS; do
      kill "$pid"
    done

    log_msg "Удаление правил маршрутизации..."
    for IP in $DEVICE_IPS; do ip rule del from $IP table $ROUTE_TABLE; done
    ip route del default dev $TUN_INTERFACE table $ROUTE_TABLE 2>/dev/null || true

    log_msg "Удаление правил фаервола..."
    log_msg "Обновление скрипта firewall-start..."
    echo "$FW_RULES" | while read -r rule; do
        manage_iptables "remove" "$rule"
        remove_script_content "$FW_SCRIPT" "iptables -I $rule"
    done

    log_msg "Обновление скрипта services-start..."
    remove_script_content "$SS_SCRIPT" "$SS_LINES"
    log_msg "sing-box остановлен."
}

setup_sing_box() {
    echo "Изменить настройки скрипта? Если sing-box запущен, при выборе варианта 2 он будет остановлен."
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Выход из меню настроек."; exit 0 ;;
            2) if is_running; then stop_sing_box; fi; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Переход к настройкам скрипта."

    source "$SBS_CONF"

    echo "Текущие IP адреса устройств: $DEVICE_IPS. Изменить их? При выборе 2 существующие IP адреса будут заменены на введённые."
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Отказ от замены IP адресов."; break ;;
            2) read -p "Введите новые IP адреса устройств: " new_ips
               DEVICE_IPS="$new_ips"
               sed -i "s|^DEVICE_IPS=\".*\"$|DEVICE_IPS=\"$new_ips\"|" "$SBS_CONF"
               log_msg "IP адреса устройств изменены."; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Редактировать config.json (конфигурационный файл sing-box) с помощью редактора nano?"
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Отказ от редактирования config.json."; break ;;
            2) echo "Открытие config.json в редакторе nano."; nano $SB_CONFIG; echo "config.json сохранён."; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Текущий номер таблицы маршрутизации: $ROUTE_TABLE. Изменить его?"
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Отказ от изменения номера таблицы маршрутизации."; break ;;
            2) read -p "Введите новый номер таблицы маршрутизации: " new_table
               ROUTE_TABLE="$new_table"
               sed -i "s|^ROUTE_TABLE=\".*\"$|ROUTE_TABLE=\"$new_table\"|" "$SBS_CONF"
               log_msg "Номер таблицы маршрутизации изменен."; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Настройки сохранены."

    sing_box_start
}

edit_sing_box() {
    echo "Редактировать sbs-conf (файл настроек скрипта) с помощью редактора nano? Если sing-box запущен, при выборе варианта 2 он будет остановлен."
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Выход."; exit 0 ;;
            2) if is_running; then stop_sing_box; fi; echo "Открытие sbs-conf в редакторе nano"; nano $SBS_CONF; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    sing_box_start
}

update_sing_box() {
    echo "Обновить скрипт sing-box? Если sing-box запущен, при выборе варианта 2 он будет остановлен."
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case "$choice" in
            1) echo "Обновление скрипта sing-box отменено."; exit 0 ;;
            2) if is_running; then stop_sing_box; fi; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Обновление скрипта sing-box..."

    curl -s -L -o "$SCRIPT_PATH" "$SCRIPT_URL"
    if [ $? -ne 0 ]; then
      echo "Ошибка: Не удалось скачать файл с $SCRIPT_URL"
      exit 1
    fi
    chmod 775 "$SCRIPT_PATH"
    echo "Основной скрипт успешно обновлён."

    cat << EOF > $TEMP_UPDATE
#!/bin/sh
rm -f $TEMP_UPDATE
exec $SCRIPT_PATH updmonandcore
EOF
    chmod 775 $TEMP_UPDATE

    exec $TEMP_UPDATE
}

updmonandcore_sing_box() {
    create_sbs_monitor "$SBS_MON"
    echo "Скрипт sbs-monitor успешно обновлён."

    create_dir "$SB_DOWNLOAD_DIR"
    curl -s -L -o "$SB_ARCHIVE_PATH" "$SB_DOWNLOAD_URL"
    tar -xzvf "$SB_ARCHIVE_PATH" -C "$SB_DOWNLOAD_DIR"
    sing_box_file=$(find "$SB_DOWNLOAD_DIR" -name "sing-box" -type f)

    echo "ООбновить файл ядра sing-box?"
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case $choice in
            1) echo "Обновление файла $SB_PATH отменено."; break ;;
            2) cp "$sing_box_file" "$SB_DIR"; chmod 775 "$SB_PATH"; echo "Файл $SB_PATH успешно обновлён."; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done
    
    rm -rf "$SB_DOWNLOAD_DIR"
    echo "Директория $SB_DOWNLOAD_DIR удалена."

    sing_box_start
}

install_sing_box() {
    echo "Установить скрипт sing-box?"
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case $choice in
            1) delete_if_not_current_dir; echo "Установка скрипта sing-box отменена."; exit 0 ;;
            2) if is_running; then
                echo "Скрипт sing-box уже установлен ранее и запущен. Продолжить установку?. При выборе варианта 2, sing-box будет предварительно остановлен."
                while true; do
                   read -p "1-Нет, 2-Да: " continue_choice
                   case "$continue_choice" in
                       1) delete_if_not_current_dir; echo "Установка скрипта sing-box отменена."; exit 0 ;;
                       2) stop_sing_box; break ;;
                       *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
                   esac
                done
               else break; fi; break ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

    echo "Начинаем установку скрипта sing-box..."

    create_or_use_existing "$JFFS_SB_DIR"

    handle_existing_file "$SCRIPT_PATH" self_copy

    ln -sf $SCRIPT_PATH $LN_PATH

    handle_existing_file "$JFFS_SB_DIR/sbs-conf" create_sbs_conf

    handle_existing_file "$SBS_MON" create_sbs_monitor

    check_file_existence_and_download "$SB_CONFIG" "https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/config.json"
    chmod 664 "$SB_CONFIG"

    if [ -n "$ROOT_DIR" ]; then
        create_or_use_existing "$SB_DIR"
    else
        echo "Директория $ROOT_DIR не найдена. Видимо в роутере отсутствует USB накопитель с установленным Entware. Операция отменена."
        delete_if_not_current_dir
        exit 1
    fi

    create_dir "$SB_DOWNLOAD_DIR"
    echo "Скачиваем архив с файлом sing-box..."
    curl -s -L -o "$SB_ARCHIVE_PATH" "$SB_DOWNLOAD_URL"
    echo "Распаковываем архив..."
    tar -xzvf "$SB_ARCHIVE_PATH" -C "$SB_DOWNLOAD_DIR"
    sing_box_file=$(find "$SB_DOWNLOAD_DIR" -name "sing-box" -type f)

    if [ -f "$SB_PATH" ]; then
        echo "Файл sing-box уже существует. Что вы хотите сделать?"
        while true; do
            read -p "1-Оставить существующий файл, 2-Заменить файл: " choice
            case $choice in
                1) echo "Оставляем существующий файл."; break ;;
                2) cp "$sing_box_file" "$SB_DIR"; chmod 775 "$SB_PATH"; echo "Файл $SB_PATH заменён"; break ;;
                *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
            esac
        done
    else
        cp "$sing_box_file" "$SB_DIR"; echo "Файл sing-box перемещён в директорию $SB_DIR"
    fi

    local current_dir=$(dirname "$(readlink -f "$0")")
    if [ "$current_dir" != "$JFFS_SB_DIR" ]; then
      rm -rf "$SB_DOWNLOAD_DIR" "$(readlink -f "$0")"
    else
      rm -rf "$SB_DOWNLOAD_DIR"
    fi

    echo "Директория $SB_DOWNLOAD_DIR удалена."

    echo "

*********************
Установка завершена.
*********************
1. Обязательно перед первым запуском sing-box выполните команду:
sbs setup
В процессе её выполнения, вы можете ввести ip адреса устройств, трафик которых желаете пустить через sing-box, отредактировать config.json (файл конфигурации sing-box) в редакторе nano, а так же сменить номер таблицы маршрутизации (не обязательно).
2. Запустить sing-box можно командой:
sbs start

Подсказки по всем командам можно увидеть, выполнив в консоли роутера команду:
sbs"
}

remove_sing_box() {
    echo "Удалить все директории и файлы скрипта sing-box? Если sing-box запущен, при выборе варианта 2 он предварительно будет остановлен."
    while true; do
        read -p "1-Нет, 2-Да: " choice
        case $choice in
            1) echo "Выход."; exit 0 ;;
            2) if is_running; then stop_sing_box; fi; echo "Удаление всех директорий и файлов скрипта sing-box."; rm -rf $SB_DIR $JFFS_SB_DIR $LN_PATH; echo "Все директории и файлы скрипта sing-box удалены."; exit 0 ;;
            *) echo "Некорректный ввод. Попробуйте ещё раз." ;;
        esac
    done

}

show_menu() {
    echo "Для запуска скрипта sing-box вы можете выполнить команду sbs с перечисленными ниже параметрами непосредственно в консоли, например sbs start, или можете выполнить запуск из данного меню по номеру параметра."
    echo "Введите номер параметра запуска или выхода из данного меню:"
    echo "1) start (Запуск sing-box)"
    echo "2) stop (Остановка sing-box)"
    echo "3) restart (Перезапуск sing-box)"
    echo "4) setup (Пошаговая настройка скрипта)"
    echo "5) edit (Редактировать файл настроек скрипта)"
    echo "6) update (Обновить файл скрипта, файл sbs-monitor и файл ядра sing-box)"
    echo "7) remove (!!!Удалить sing-box полностью!!!)"
    echo "8) Выход из меню."
}

# Меню
case "$1" in
    install) install_sing_box ;;
    setup) setup_sing_box ;;
    start) start_sing_box ;;
    stop) stop_sing_box ;;
    restart) stop_sing_box && start_sing_box ;;
    edit) edit_sing_box ;;
    update) update_sing_box ;;
    remove) remove_sing_box ;;
    updmonandcore) updmonandcore_sing_box ;;
    *)
        while true; do
            show_menu
            read -p "Enter your choice [1-7]: " choice
            case $choice in
                1) start_sing_box; break ;;
                2) stop_sing_box; break ;;
                3) stop_sing_box && start_sing_box; break ;;
                4) setup_sing_box; break ;;
                5) edit_sing_box; break ;;
                6) update_sing_box; break ;;
                7) remove_sing_box; break ;;
                8) exit 0 ;;
                *) echo "Некорректный ввод, попробуйте ещё." ;;
            esac
        done ;;
esac