#!/bin/sh
# Для SBS 1.8

# Переменные
ROOT_DIR="/opt/root"
TEMP_SBS_DIR="$ROOT_DIR/temp_sbs"
TEMP_LANG_RU="$TEMP_SBS_DIR/lang-ru"
TEMP_LANG_EN="$TEMP_SBS_DIR/lang-en"
TEMP_SBS_CONF="$TEMP_SBS_DIR/sbs-conf"
TEMP_SBS="$TEMP_SBS_DIR/sbs"

# Установка
rm -rf $TEMP_SBS && mkdir $TEMP_SBS
wget -P $TEMP_SBS_DIR https://raw.githubusercontent.com/Dr4tez/sing-box4asus/Dev/lang-ru && chmod 664 $TEMP_LANG_RU
wget -P $TEMP_SBS_DIR https://raw.githubusercontent.com/Dr4tez/sing-box4asus/Dev/lang-en && chmod 664 $TEMP_LANG_EN
wget -P $TEMP_SBS_DIR https://raw.githubusercontent.com/Dr4tez/sing-box4asus/Dev/sbs-conf && chmod 664 $TEMP_SBS_CONF
wget -P $TEMP_SBS_DIR https://raw.githubusercontent.com/Dr4tez/sing-box4asus/Dev/sbs && chmod 775 $TEMP_SBS

echo "Выбор языка / Select language:"
while true; do
    read -p " 1 - Русский / Russian
 2 - Aнглийский / English
 0 - Выход / Exit
Введите номер пункта / Enter item number: " language_choice
    case "$language_choice" in
        1) source "$TEMP_LANG_RU"; sed -i 's/^LANG=".*"/LANG="ru"/' "$TEMP_SBS_CONF"; break ;;
        2) source "$TEMP_LANG_EN"; sed -i 's/^LANG=".*"/LANG="en"/' "$TEMP_SBS_CONF"; break ;;
        0) exit 0 ;;
        *) echo "Некорректный ввод. Попробуйте ещё раз. / Invalid input. Please try again." ;;
    esac
done

inst_sing_box() {
echo "$MESSAGE158"
while true; do
    read -p "$MESSAGE18" choice
    case $choice in
        0) delete_if_not_current_dir; echo "$MESSAGE159"; exit 0 ;;
        1) if is_running; then
            echo "$MESSAGE160"
            while true; do
                read -p "$MESSAGE18" continue_choice
                case "$continue_choice" in
                    0) delete_if_not_current_dir; echo "$MESSAGE159"; exit 0 ;;
                    1) stop_sing_box; break ;;
                    *) echo "$MESSAGE6" ;;
                esac
            done
           else break; fi; break ;;
        *) echo "$MESSAGE6" ;;
    esac
done

    echo "$MESSAGE161"
    create_or_use_existing "$JFFS_SB_DIR"
    handle_existing_file "$SCRIPT_PATH" self_copy
    ln -sf $SCRIPT_PATH $LN_PATH
    handle_existing_file "$JFFS_SB_DIR/sbs-conf" create_sbs_conf
    handle_existing_file "$SBS_MON" create_sbs_monitor
    check_file_existence_and_download "$SB_CONFIG" "$SB_CONFIG_URL"
    chmod 664 "$SB_CONFIG"

    if [ -n "$ROOT_DIR" ]; then
        create_or_use_existing "$SB_DIR"
    else
        echo "$MESSAGE162"
        delete_if_not_current_dir
        exit 1
    fi

    create_dir "$SB_DOWNLOAD_DIR"
    if [ "$(uname -m)" = "aarch64" ]; then
        DOWNLOAD_URL="$SB_DOWNLOAD64_URL"
        ARCHIVE_PATH="$SB_ARCHIVE64_PATH"
    else
        DOWNLOAD_URL="$SB_DOWNLOAD_URL"
        ARCHIVE_PATH="$SB_ARCHIVE_PATH"
    fi
    echo "$MESSAGE163"
    wget -q -O "$ARCHIVE_PATH" "$DOWNLOAD_URL"
    echo "$MESSAGE164"
    tar -xzvf "$ARCHIVE_PATH" -C "$SB_DOWNLOAD_DIR"
    sing_box_file=$(find "$SB_DOWNLOAD_DIR" -name "sing-box" -exec test -f {} \; -print)

    if [ -f "$SB_PATH" ]; then
        echo "$MESSAGE165"
        while true; do
            read -p "$MESSAGE12" choice
            case $choice in
                0) echo "$MESSAGE13"; break ;;
                1) if [ -f "$sing_box_file" ]; then
                    cp "$sing_box_file" "$SB_DIR"; chmod 775 "$SB_PATH"; echo "$MESSAGE166"; break
                else
                    echo "$MESSAGE167"; break
                fi ;;
                *) echo "$MESSAGE6" ;;
            esac
        done
    else
        if [ -f "$sing_box_file" ]; then
            cp "$sing_box_file" "$SB_DIR"; echo "$MESSAGE168"
        else
            echo "$MESSAGE169"
        fi
    fi

    local current_dir=$(dirname "$(readlink -f "$0")")
    if [ "$current_dir" != "$JFFS_SB_DIR" ]; then
      rm -rf "$SB_DOWNLOAD_DIR" "$(readlink -f "$0")"
    else
      rm -rf "$SB_DOWNLOAD_DIR"
    fi

    echo "$MESSAGE170"
    echo ""
    echo "$MESSAGE171"
}

# Обновитель
update_sing_box() {
    echo ""
    echo "$MESSAGE100"
    wget -q -O "$SCRIPT_PATH"-tmp "$SCRIPT_URL"
    silent_create_dir "$SB_DOWNLOAD_DIR"
    if [ "$(uname -m)" = "aarch64" ]; then
        DOWNLOAD_URL="$SB_DOWNLOAD64_URL"
        ARCHIVE_PATH="$SB_ARCHIVE64_PATH"
    else
        DOWNLOAD_URL="$SB_DOWNLOAD_URL"
        ARCHIVE_PATH="$SB_ARCHIVE_PATH"
    fi
    wget -q -O "$ARCHIVE_PATH" "$DOWNLOAD_URL"
    tar -xzvf "$ARCHIVE_PATH" -C "$SB_DOWNLOAD_DIR" > /dev/null
    echo "$MESSAGE101"
    update_sing_box_menu
}

update_sing_box_menu() {
    singbox_file=$(find "$SB_DOWNLOAD_DIR" -name "sing-box" -exec test -f {} \; -print)
    chmod 775 $singbox_file
    sbs_vers=$(get_sbs_version $SCRIPT_PATH)
    sb_vers=$(get_sb_version $SB_PATH)
    sbs_vers_new=$(get_sbs_version "$SCRIPT_PATH"-tmp)
    sb_vers_new=$(get_sb_version $singbox_file)

    while true; do
        echo ""
        echo "$MESSAGE102"
        echo "$MESSAGE103"
        printf "$MESSAGE104\n" "$sbs_vers" "$sbs_vers_new"
        printf "$MESSAGE105\n" "$sb_vers" "$sb_vers_new"
        echo "$MESSAGE95"
        read -p "$MESSAGE47" choice
        case "$choice" in
            1) is_running && stop_sing_box; update_sbs; break ;;
            2) is_running && stop_sing_box; updcore_sing_box; break ;;
            0) rm -f "$SCRIPT_PATH"-tmp; rm -rf "$SB_DOWNLOAD_DIR"; echo "$MESSAGE106"; is_running || sing_box_start; exit 0 ;;
            *) echo "$MESSAGE6" ;;
        esac
    done
}

update_sbs() {
    echo ""
    echo "$MESSAGE107"
    cp "$SCRIPT_PATH"-tmp $SCRIPT_PATH
    chmod 775 $SCRIPT_PATH

    cat << EOF > $TEMP_UPDATE
#!/bin/sh
rm -f $TEMP_UPDATE
exec $SCRIPT_PATH updmonandcore
EOF
    chmod 775 $TEMP_UPDATE

    exec $TEMP_UPDATE
}

updmonandcore_sing_box() {
    create_sbs_monitor "$SBS_MON"
    echo "$MESSAGE108"
    update_sing_box_menu
}

updcore_sing_box() {
    echo ""
    echo "$MESSAGE109"
    cp "$singbox_file" "$SB_DIR"; echo "$MESSAGE110"
    update_sing_box_menu
}

# Удалитель
remove_sing_box() {
    echo "$MESSAGE172"
    while true; do
        read -p "$MESSAGE18" choice
        case $choice in
            0) echo "$MESSAGE173"; exit 0 ;;
            1) is_running && stop_sing_box; echo "$MESSAGE174"; rm -rf $SB_DIR $JFFS_SB_DIR $LN_PATH; echo "$MESSAGE175"; exit 0 ;;
            *) echo "$MESSAGE6" ;;
        esac
    done
}
