#!/bin/sh

JFFS_SING_BOX_DIR="/jffs/addons/sing-box"
CONFIG_FILE="$JFFS_SING_BOX_DIR/sing-box-script-ru.conf"

create_dir() {
    mkdir -p "$1"
    chmod 775 "$1"
    echo "Директория $1 создана."
}

dir_exists() {
    [ -d "$1" ]
}

create_config() {
    cat << EOF > "$1"
# Этот файл создаётся автоматически и значения вводятся через консоль при выполнении команды sbs setup.
# Если хотите изменить значения тут с помощью редактора, то перед этим обязательно остановите sing-box через консоль командой sbs stop
# Впишите в кавычки, в одну строку, разделенные пробелами ip-адреса устройств, трафик которых надо направить в tun интерфейс sing-box.
DEVICE_IPS="192.168.50.31 192.168.50.32"

# Если указанный дефолтный номер 555 таблицы маршрутизации на вашем маршрутизаторе уже занят, что маловероятно, назначьте другой номер, не занятый.
ROUTE_TABLE="555"
EOF
    chmod 664 "$1"
}

root_dir=$(find /mnt/ -depth -type d -name root | head -n 1)

check_file_existence_and_download() {
    local file_path="$1"
    local file_url="$2"
    local file_name=$(basename "$file_path")

    if [ -f "$file_path" ]; then
        while true; do
            read -p "Файл $file_name уже существует. Что вы хотите сделать? 
(1: Пропустить скачивание, 2: Скачать и заменить файл): " choice
            case $choice in
                1) echo "Пропускаем скачивание $file_name."; return 0 ;;
                2) echo "Скачиваем и заменяем файл $file_name"; curl -s -L -o "$file_path" "$file_url"; return 0 ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        echo "Скачиваем $file_name..."
        curl -s -L -o "$file_path" "$file_url"
    fi
}

create_or_use_existing() {
    local dir_path="$1"
    if dir_exists "$dir_path"; then
        while true; do
            read -p "Директория $dir_path уже существует. Что вы хотите сделать? 
(1: Завершить работу, 2: Использовать существующую директорию): " choice
            case $choice in
                1) rm -rf /jffs/scripts/sing-box-script-install-ru ; echo "Работа скрипта завершена."; exit 0 ;;
                2) echo "Используем существующую директорию $dir_path"; break ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        create_dir "$dir_path"
    fi
}

handle_existing_file() {
    local file_path="$1"
    local create_function="$2"
    if [ -f "$file_path" ]; then
        while true; do
            read -p "Файл $file_path уже существует. Что вы хотите сделать? 
(1: Оставить существующий файл, 2: Заменить файл): " choice
            case $choice in
                1) echo "Оставляем существующий файл."; break ;;
                2) echo "Заменяем файл $file_path"; "$create_function" "$file_path"; break ;;
                *) echo "Неверный выбор. Попробуйте еще раз." ;;
            esac
        done
    else
        "$create_function" "$file_path"
    fi
}

create_or_use_existing "$JFFS_SING_BOX_DIR"

SCRIPT_URL="https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/sing-box-script-ru"
SCRIPT_PATH="$JFFS_SING_BOX_DIR/sing-box-script-ru"
check_file_existence_and_download "$SCRIPT_PATH" "$SCRIPT_URL"
chmod 775 $SCRIPT_PATH

ln -sf "$SCRIPT_PATH" /opt/bin/sbs

handle_existing_file "$CONFIG_FILE" create_config

CONFIG_URL="https://raw.githubusercontent.com/Dr4tez/sing-box4asus/main/config.json"
CONFIG_PATH="$JFFS_SING_BOX_DIR/config.json"
check_file_existence_and_download "$CONFIG_PATH" "$CONFIG_URL"
chmod 664 "$CONFIG_PATH"

if [ -n "$root_dir" ]; then
    SING_BOX_DIR="$root_dir/sing-box"
    create_or_use_existing "$SING_BOX_DIR"
else
    echo "Директория 'root' не найдена в /mnt. Операция отменена."
    exit 1
fi

URL="https://api.github.com/repos/SagerNet/sing-box/releases/latest"
ARCHIVE_FILE="sing-box-linux-arm64.tar.gz"
DOWNLOAD_DIR="$SING_BOX_DIR/sing-box-download"

create_dir "$DOWNLOAD_DIR"

DOWNLOAD_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" "$URL" | grep -o '"browser_download_url":\s*"[^"]*linux-arm64.tar.gz"' | grep -o 'https://.*linux-arm64.tar.gz')

if [ -z "$DOWNLOAD_URL" ]; then
    echo "Не удалось найти ссылку на скачивание архива."
    exit 1
fi

FULL_PATH="$DOWNLOAD_DIR/$ARCHIVE_FILE"

echo "Скачиваем архив..."
curl -s -L -o "$FULL_PATH" "$DOWNLOAD_URL"

echo "Распаковываем архив..."
tar -xzvf "$FULL_PATH" -C "$DOWNLOAD_DIR"

sing_box_file=$(find "$DOWNLOAD_DIR" -name "sing-box" -type f)

if [ -z "$sing_box_file" ]; then
    echo "Не удалось найти файл sing-box в распакованном архиве."
    exit 1
fi

sing_box_path="$SING_BOX_DIR/sing-box"
if [ -f "$sing_box_path" ]; then
    while true; do
        read -p "Файл sing-box уже существует. Что вы хотите сделать? 
(1: Оставить существующий файл, 2: Заменить файл): " choice
        case $choice in
            1) echo "Оставляем существующий файл."; break ;;
            2) echo "Заменяем файл $sing_box_path"; cp "$sing_box_file" "$SING_BOX_DIR/"; chmod 775 "$sing_box_path"; break ;;
            *) echo "Неверный выбор. Попробуйте еще раз." ;;
        esac
    done
else
    cp "$sing_box_file" "$SING_BOX_DIR"; echo "Файл sing-box перемещён в директорию $SING_BOX_DIR"
fi

rm -rf "$DOWNLOAD_DIR" /jffs/scripts/sing-box-script-install-ru

echo "Директория $DOWNLOAD_DIR удалена."

echo "

*********************
Установка завершена.
*********************
Следующим шагом вы должны отредактировать под себя config.json - файл конфигурации sing-box, расположенный по пути $CONFIG_PATH.
Можете сделать это с помощью WinSCP или в консоли роутера командой:
sbs edit
Затем для настройки скрипта sing-box выполнить:
sbs setup
Подсказки по всем командам можете увидеть, выполнив в консоли роутера команду:
sbs"
