#!/bin/sh

# Скрипт для запуска sing-box на роутерах Asus с прошивкой Мерлина и установленным на USB носителе Entware.

# Статические переменные
SB_CONFIG="/jffs/addons/sing-box/config.json"
SCRIPT_PATH="/jffs/addons/sing-box/sing-box-script-ru"
SCRIPT_CONF="/jffs/addons/sing-box/script-conf"
SB_PATH="/opt/root/sing-box/sing-box"
SS_SCRIPT="/jffs/scripts/services-start"
SS_LINES="sleep 30
/jffs/addons/sing-box/sing-box-script-ru start"
FW_SCRIPT="/jffs/scripts/firewall-start"

# Подключение файла с конфигурацией
source "$SCRIPT_CONF"

# Правила файрвола
FW_RULES="FORWARD -i $TUN_INTERFACE -j ACCEPT
FORWARD -o $TUN_INTERFACE -j ACCEPT
INPUT -i $TUN_INTERFACE -j ACCEPT
OUTPUT -o $TUN_INTERFACE -j ACCEPT"

# Функции
log_msg() {
    echo "$1"
    logger -t "sing-box" "$1"
}

ensure_script() {
    [ -f "$1" ] || { echo "#!/bin/sh" > "$1"; chmod 755 "$1"; }
}

update_script() {
    ensure_script "$1"
    echo "$2" | while read -r line; do
        grep -qF "$line" "$1" || echo "$line" >> "$1"
    done
}

remove_script_content() {
    [ -f "$1" ] && echo "$2" | while read -r line; do
        sed -i "/$(echo "$line" | sed 's/[\/&]/\\&/g')/d" "$1"
    done
}

manage_iptables() {
    if [ "$1" = "add" ]; then
        iptables -C $2 2>/dev/null || iptables -I $2 || log_msg "Error adding iptables rule: $2"
    elif [ "$1" = "remove" ]; then
        iptables -C $2 2>/dev/null && iptables -D $2 || log_msg "Error removing iptables rule: $2"
    fi
}

is_running() {
    ps | grep -v grep | grep -q "$SB_PATH"
}

update_tun() {
    if [ -f "$SB_CONFIG" ]; then
        local config_content=$(cat "$SB_CONFIG")
        local new_iface=$(echo "$config_content" | grep '"interface_name":' | sed -n 's/.*"interface_name": "\(.*\)".*/\1/p')
        if [ -n "$new_iface" ] && [ "$new_iface" != "$TUN_INTERFACE" ]; then
            TUN_INTERFACE="$new_iface"
            sed -i "s|^TUN_INTERFACE=\".*\"$|TUN_INTERFACE=\"$TUN_INTERFACE\"|" "$SCRIPT_CONF"
            log_msg "Имя интерфейса TUN обновлено на: $TUN_INTERFACE"
        elif [ -z "$new_iface" ]; then
            log_msg "Ошибка: не удалось извлечь имя интерфейса TUN из $SB_CONFIG"
            exit 1
        fi
    else
        log_msg "Ошибка: файл $SB_CONFIG не найден"
        exit 1
    fi

    echo "Настройки сохранены."

    while true; do
        read -p "Запустить sing-box? (1-Нет 2-Да): " choice
        case "$choice" in
            1) echo "sing-box не запущен." ; break ;;
            2) start_sing_box ; break ;;
            *) echo "Некорректный ввод: Введите 1 или 2." ;;
        esac
    done
}

setup_sing_box() {
    read -p "Изменить настройки скрипта? Если sing-box запущен, при выборе варианта 2 он будет остановлен. (1-Нет 2-Да): " choice
    case "$choice" in
        1) echo "Выход из меню настроек." ; exit 0 ;;
        2) if is_running; then stop_sing_box ; echo "Переход к настройкам скрипта." ; fi ;;
        *) echo "Некорректный ввод: Введите 1 или 2." ;;
    esac

    echo "Текущие IP адреса устройств: $DEVICE_IPS"
    while true; do
        read -p "Изменить IP адреса устройств? (1-Нет 2-Да): " choice
        case "$choice" in
            1) break ;;
            2) read -p "Введите новые IP адреса устройств: " new_ips
               DEVICE_IPS="$new_ips"
               sed -i "s|^DEVICE_IPS=\".*\"$|DEVICE_IPS=\"$new_ips\"|" "$SCRIPT_CONF"
               log_msg "IP адреса устройств изменены." ; break ;;
            *) echo "Некорректный ввод: Введите 1 или 2." ;;
        esac
    done

    echo "Текущий номер таблицы маршрутизации: $ROUTE_TABLE"
    while true; do
        read -p "Изменить номер таблицы маршрутизации? (1-Нет 2-Да): " choice
        case "$choice" in
            1) break ;;
            2) read -p "Введите новый номер таблицы маршрутизации: " new_table
               ROUTE_TABLE="$new_table"
               sed -i "s|^ROUTE_TABLE=\".*\"$|ROUTE_TABLE=\"$new_table\"|" "$SCRIPT_CONF"
               log_msg "Номер таблицы маршрутизации изменен." ; break ;;
            *) echo "Некорректный ввод: Введите 1 или 2." ;;
        esac
    done

    update_tun
}

start_sing_box() {
    log_msg "Запуск sing-box..."
    is_running && { log_msg "Ошибка: sing-box уже запущен"; exit 1; }

    lsmod | grep -q "^tun " || { log_msg "Загрузка модуля TUN..."; modprobe tun; }

    $SB_PATH run -c $SB_CONFIG &
    sleep 3

    ip link show $TUN_INTERFACE >/dev/null 2>&1 || { log_msg "Ошибка: интерфейс TUN $TUN_INTERFACE не найден"; exit 1; }

    log_msg "Настройка таблицы маршрутизации..."
    ip route add default dev $TUN_INTERFACE table $ROUTE_TABLE
    for IP in $DEVICE_IPS; do ip rule add from $IP table $ROUTE_TABLE; done

    log_msg "Добавление правил фаервола..."
    echo "$FW_RULES" | while read -r rule; do
        manage_iptables "add" "$rule"
    done

    log_msg "Обновление скрипта firewall-start..."
    echo "$FW_RULES" | while read -r rule; do
        update_script "$FW_SCRIPT" "iptables -I $rule"
    done

    log_msg "Обновление скрипта services-start..."
    update_script "$SS_SCRIPT" "$SS_LINES"
    log_msg "sing-box запущен."

    /jffs/addons/sing-box/monitor-routes &
}

stop_sing_box() {
    log_msg "Остановка sing-box..."

    pids=$(pidof "monitor-routes")
    if [ -z "$pids" ]; then
      break
    fi
    for pid in $pids; do
      kill "$pid"
    done

    PIDS=$(pidof "sing-box")
    if [ -z "$PIDS" ]; then
      break
    fi
    for pid in $PIDS; do
      kill "$pid"
    done

    log_msg "Удаление правил маршрутизации..."
    for IP in $DEVICE_IPS; do ip rule del from $IP table $ROUTE_TABLE; done
    ip route del default dev $TUN_INTERFACE table $ROUTE_TABLE 2>/dev/null || true

    log_msg "Удаление правил фаервола..."
    log_msg "Обновление скрипта firewall-start..."
    echo "$FW_RULES" | while read -r rule; do
        manage_iptables "remove" "$rule"
        remove_script_content "$FW_SCRIPT" "iptables -I $rule"
    done

    log_msg "Обновление скрипта services-start..."
    remove_script_content "$SS_SCRIPT" "$SS_LINES"
    log_msg "sing-box остановлен."
}

edit_sing_box() {
    read -p "Редактировать конфигурационный файл sing-box config.json с помощью редактора nano? Если sing-box запущен, при выборе варианта 2 он будет остановлен. 
(1-Нет 2-Да): " choice
    case "$choice" in
        1) echo "Выход." ; exit 0 ;;
        2) if is_running; then stop_sing_box ; echo "Открытие config.json в редакторе nano" ; nano $SB_CONFIG ; update_tun ; fi ;;
        *) echo "Некорректный ввод: Введите 1 или 2." ;;
    esac
}

remove_sing_box() {
    read -p "Удалить все директории и файлы скрипта sing-box? Если sing-box запущен, при выборе варианта 2 он предварительно будет остановлен. 
(1-Нет 2-Да): " choice
    case "$choice" in
        1) echo "Выход." ; exit 0 ;;
        2) if is_running; then stop_sing_box ; echo "Удаление всех директорий и файлов скрипта sing-box." ; rm -rf /opt/root/sing-box /jffs/addons/sing-box /opt/bin/sbs ; echo "Все директории и файлы скрипта sing-box удалены." ; fi ;;
        *) echo "Некорректный ввод: Введите 1 или 2." ;;
    esac
}

show_menu() {
    echo "Для запуска скрипта sing-box вы можете выполнить команду sbs с перечисленными ниже параметрами непосредственно в консоли, например sbs start, или можете выполнить запуск из данного меню по номеру параметра."
    echo "Введите номер параметра запуска или выхода из данного меню:"
    echo "1) start (запуск sing-box)"
    echo "2) stop (остановка sing-box)"
    echo "3) restart (перезапуск sing-box)"
    echo "4) setup (настройка скрипта)"
    echo "5) edit (редактировать config.json - конфигурационный файл sing-box)"
    echo "6) remove (!!!удалить все директории и файлы скрипта sing-box!!!)"
    echo "7) Выход из меню."
}

# Меню
case "$1" in
    start) start_sing_box ;;
    stop) stop_sing_box ;;
    restart) stop_sing_box && start_sing_box ;;
    setup) setup_sing_box ;;
    edit) edit_sing_box ;;
    remove) remove_sing_box ;;
    *)
        while true; do
            show_menu
            read -p "Enter your choice [1-7]: " choice
            case $choice in
                1) start_sing_box; break ;;
                2) stop_sing_box; break ;;
                3) stop_sing_box && start_sing_box; break ;;
                4) setup_sing_box; break ;;
                5) edit_sing_box; break ;;
                6) remove_sing_box; break ;;
                7) exit 0 ;;
                *) echo "Некорректный ввод, попробуйте ещё." ;;
            esac
        done
        ;;
esac